name: Build Kivy APK

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    # ================= PYTHON 3.10 =================
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # ================= SYSTEM =================
    - name: Install System Dependencies
      run: |
        sudo add-apt-repository -y universe
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip curl wget \
          build-essential \
          openjdk-17-jdk \
          pkg-config zlib1g-dev libffi-dev libssl-dev \
          libgl1-mesa-dev \
          libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
          autoconf libtool cmake \
          libncurses5-dev

    # ================= PYTHON TOOLS =================
    - name: Install Build Tools
      run: |
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install cython buildozer

    # ================= ANDROID SDK =================
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Accept Licenses
      run: yes | sdkmanager --licenses

    - name: Install Android SDK (STABLE)
      run: |
        sdkmanager --uninstall "build-tools;36.1.0" || true
        sdkmanager --install \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.2" \
          "ndk;23.1.7779620"

    # ================= FIX python-for-android =================
    - name: Clone python-for-android MANUAL
      run: |
        mkdir -p .buildozer/android/platform
        cd .buildozer/android/platform
        git clone https://github.com/kivy/python-for-android.git

    # ================= BUILD APK =================
    - name: Build APK
      env:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      run: |
        buildozer --version
        buildozer android clean
        buildozer android debug

    # ================= UPLOAD =================
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: bin/*.apk
