name: Build Kivy APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  SKIP_JDK_VERSION_CHECK: 1
  ANDROID_BUILD_TOOLS_VERSION: 33.0.2

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    # =========================
    # JAVA 17
    # =========================
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - run: java -version

    # =========================
    # ANDROID SDK
    # =========================
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    # =========================
    # FORCE BUILD TOOLS 33
    # =========================
    - name: Install Android Build Tools 33 (FORCED)
      run: |
        yes | sdkmanager --licenses

        # HAPUS SEMUA BUILD TOOLS
        sdkmanager --uninstall "build-tools;36.0.0" || true
        sdkmanager --uninstall "build-tools;36.1.0" || true

        # INSTALL YANG DIPERLUKAN SAJA
        sdkmanager --install \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.2" \
          "ndk;23.1.7779620"

        # PAKSA PATH KE BUILD-TOOLS 33
        echo "$ANDROID_HOME/build-tools/33.0.2" >> $GITHUB_PATH

        # CEK AIDL
        which aidl
        aidl --version

    # =========================
    # PYTHON 3.10
    # =========================
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # =========================
    # SYSTEM LIBS
    # =========================
    - run: |
        sudo apt update
        sudo apt install -y \
          zip unzip git \
          build-essential \
          ccache \
          libffi-dev \
          libssl-dev \
          libgl1-mesa-dev

    # =========================
    # PYTHON TOOLS
    # =========================
    - run: |
        python -m pip install --upgrade pip
        pip install buildozer
        pip install cython==0.29.36
        pip install appdirs
        pip install python-for-android

    # =========================
    # CLEAN CACHE TOTAL
    # =========================
    - run: |
        rm -rf .buildozer
        rm -rf ~/.buildozer

    # =========================
    # BUILD APK
    # =========================
    - name: Build APK
      run: buildozer android debug

    # =========================
    # UPLOAD APK
    # =========================
    - uses: actions/upload-artifact@v4
      with:
        name: MultiDownloaderID-APK
        path: bin/*.apk
