name: Build Kivy APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    # =========================
    # JAVA 17 (WAJIB)
    # =========================
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - run: java -version

    # =========================
    # ANDROID SDK
    # =========================
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    # =========================
    # INSTALL BUILD TOOLS 33 (BUKAN 36)
    # =========================
    - name: Install Android Packages (LOCKED)
      run: |
        sdkmanager --uninstall "build-tools;36.0.0" || true
        sdkmanager --uninstall "build-tools;36.1.0" || true

        yes | sdkmanager --licenses

        sdkmanager --install \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.2" \
          "ndk;23.1.7779620"

    # =========================
    # PYTHON 3.10 (WAJIB)
    # =========================
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # =========================
    # SYSTEM LIBS
    # =========================
    - run: |
        sudo apt update
        sudo apt install -y \
          zip unzip git \
          build-essential \
          ccache \
          libffi-dev \
          libssl-dev \
          libgl1-mesa-dev \
          default-jdk

    # =========================
    # PYTHON TOOLS
    # =========================
    - run: |
        python -m pip install --upgrade pip
        pip install buildozer
        pip install cython==0.29.36
        pip install appdirs
        pip install python-for-android

    # =========================
    # CLEAN TOTAL CACHE
    # =========================
    - run: |
        rm -rf .buildozer
        rm -rf ~/.buildozer

    # =========================
    # BUILD
    # =========================
    - name: Build APK
      run: buildozer android debug

    # =========================
    # UPLOAD
    # =========================
    - uses: actions/upload-artifact@v4
      with:
        name: MultiDownloaderID-APK
        path: bin/*.apk
